server:
  port: 9092

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: review
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      dll-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mars
    username: root
    password: lefbluegr

security:
  oauth2:
    resource:
      jwt:
        key-value: marscolonySigningKey

