server:
  port: 9091

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: review

#security:
 # oauth2:
  #  resource:
   #   jwt:
    #    key-value: marscolonySigningKey